# Generated by Django 5.2.3 on 2025-06-18 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realmate_challenge_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='started_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='closed_at',
        ),
    ]
