# Generated by Django 5.2.3 on 2025-06-19 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realmate_challenge_app', '0003_rename_conversation_message_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(choices=[('INBOUND', 'Inbound'), ('OUTBOUND', 'Outbound')], default='INBOUND', max_length=8),
        ),
    ]
