# Generated by Django 5.2.3 on 2025-06-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realmate_challenge_app', '0004_conversation_timestamp_alter_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
