# Generated by Django 5.2.3 on 2025-06-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realmate_challenge_app', '0006_alter_message_conversation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expected_conversation_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
